name: LocksAndLockpicking
version: 1.0
main: io.github.mathias0903.MultiBlockActions.Main
api-version: 1.14
softdepend: [PlaceholderAPI]
depend: [WorldEdit]
commands:
  mulitblock:
    description: main command for MultiBlock Actions
    usage: /multiblock (sub command) (args)
    aliases: [mba, mb, Multi]